import * as React from "react";
import Box from "@mui/material/Box";
import InputLabel from "@mui/material/InputLabel";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";
import Select, { SelectChangeEvent } from "@mui/material/Select";

type BasicSelectProps = {
  label: string;
  idAttribute: string;
};

const BasicSelect: React.FC<BasicSelectProps> = ({ label, idAttribute }) => {
  const [choice, setChoice] = React.useState("");

  const handleChange = (event: SelectChangeEvent) => {
    setChoice(event.target.value as string);
  };

  React.useEffect(() => {
    console.log(choice);
  },[choice])

  return (
    <Box sx={{ minWidth: 300 }}>
      <FormControl fullWidth>
        <InputLabel id={`${idAttribute}-label`}>{label}</InputLabel>
        <Select
          labelId={`${idAttribute}-label`}
          id={`${idAttribute}-select`}
          value={choice}
          label={label}
          onChange={handleChange}
        >
          {/* These values will be generated by API data */}
          <MenuItem value={10}>Ten</MenuItem>
          <MenuItem value={20}>Twenty</MenuItem>
          <MenuItem value={30}>Thirty</MenuItem>
        </Select>
      </FormControl>
    </Box>
  );
};

export default BasicSelect;
